import mongoose from "mongoose";

const orderSchema = new mongoose.Schema(
  {
    tenantId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Tenant",
      required: true,
    },
    customerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Customer",
      required: true,
    },
    // Human-readable order number, unique per tenant
    // e.g., "ORD-2024-001" — generated by application logic, not the DB
    orderNumber: {
      type: String,
      required: true,
      trim: true,
    },
    orderDate: {
      type: Date,
      default: Date.now,
    },
    deliveryDate: {
      type: Date,
      default: null,
    },
    // Snapshot of the sum of all OrderItem prices before discount
    subtotal: {
      type: Number,
      required: true,
      min: 0,
    },
    discount: {
      type: Number,
      default: 0,
      min: 0,
    },
    discountType: {
      type: String,
      enum: ["fixed", "percentage"],
      default: "fixed",
    },
    // Final amount the customer owes — calculated at order creation, never recalculated
    total: {
      type: Number,
      required: true,
      min: 0,
    },
    // Updated by application logic after each Payment is recorded
    paymentStatus: {
      type: String,
      enum: ["unpaid", "partial", "paid"],
      default: "unpaid",
    },
    // Updated by application logic as OrderItems progress through the workflow
    productionStatus: {
      type: String,
      enum: ["pending", "in_progress", "completed", "delivered", "cancelled"],
      default: "pending",
    },
    notes: {
      type: String,
      trim: true,
    },
  },
  { timestamps: true },
);

// Order number is unique within a tenant (two tenants can both have "ORD-001")
orderSchema.index({ tenantId: 1, orderNumber: 1 }, { unique: true });

// Dashboard: filter orders by production state for this shop
orderSchema.index({ tenantId: 1, productionStatus: 1 });

// Dashboard: filter orders by payment state for this shop
orderSchema.index({ tenantId: 1, paymentStatus: 1 });

// Customer order history
orderSchema.index({ tenantId: 1, customerId: 1 });

// Upcoming delivery view — sorted by delivery date
orderSchema.index({ tenantId: 1, deliveryDate: 1 });

export default mongoose.model("Order", orderSchema);
